### PR TITLE
STDM configuration upgrade module

### PR DESCRIPTION
**Pull request by geonomad-consulting**
## Proposed changes in this pull request
This pull request contain the main functionality for upgrading old stdmConfig.xml to new version configuration.stc. The upgrade process parses through old stdmConfig.xml extracts it's tables, relations and lookup content, gets necessary information like column names, description, codes, geometry information and other information and finally populated it to new entities, value list and relations. 

In addition, the new module converts column data types in the old stdm that was predominantly varying character to new stdm version 1.2 data types that now includes GEOMETRY, DATE, revamped LOOKUP and other column types.

This module also allows users to migrate data from previous installation of stdm. The migration currently only focuses on tables that participates in social tenure relationship, others could be added in the future if deemed necessary.

stdm_config_file_upgrade_activity_v1 2

### CODE REVIEW

**Comment by wondie** [comment]
This branch still has issues. I suggest not to merge it with ref_config_mod as @pgathogo is going to use ref_config_mod to create the installer for tomorrow.

**Comment by gkahiu** [comment]
@wondie and @eomwandho, many thanks for finalizing this. I just have one comment - I have randomly reviewed some of the code and I have noticed that you are using the `str()` function which if used for converting user values, will result in nasty errors for non-ASCII characters. If using for converting numeric values to string then that is fine but if it is string values then please refactor to use the `unicode()` function. Once this is finalized then we can proceed to merge.

**Comment by wondie** [comment]
@gkahiu because @geonomad-consulting / @eomwandho couldn't pull the latest changes, let me fix where str() is used.

**Comment by wondie** [comment]
@gkahiu I have just pushed the fix.

**Pull request merged**
