### PR TITLE
upload file or folder containing many shapefiles/csv/autocad file + minor cleanups

### PR DESCRIPTION
**Pull request by biplovbhandari**

### CODE REVIEW

**Comment by wondie** [comment]
Thank you very much for the contribution Biplov! Did you add any updates since we talked about it in the workshop?

**Comment by biplovbhandari** [comment]
Just the label Wondi. Nothing else. However I have added them as TODOs [here](https://github.com/gltn/stdm/pull/308/files#diff-a0e3473636228154bff146e71329fa4bR20).

**Comment by wondie** [comment]
@biplovbhandari that is noted. I will add you to transifex right away. Thanks!
Just one note for future commits, PEP8 recommends single quote than double quotes. I will make the change for the merged commit.

**Comment by biplovbhandari** [comment]
@wondie thanks! I saw mixed quotes so I changed to double. In future, I will use single quotes! Thanks for notifying

**Comment by wondie** [comment]
You are welcome. That is understandable.

**Pull request merged**
